### ISSUE TITLE
Should we have parity with ppa-generated source filename?

### ISSUE THREAD

**Issue by qnm** [brwyatt/puppet-flatpak#2]
If I install flatpak using `add-apt-repository ppa:alexlarsson/flatpak`, my source list in `/etc/apt/sources.list.d` has the filename `alexlarsson-ubuntu-flatpak-zesty.list`.

Should this package also adopt the same naming format?

**Comment by brwyatt** [comment]
That's a good point.Should definitely be the default. I'll get something out for this today if I can.
